### ISSUE TITLE
[Windows] Miss leading error message logging in FileRead

### ISSUE THREAD

**Issue by poon3310** [notestsoft/breaklee#108]
How to fix?
![image](https://github.com/notestsoft/breaklee/assets/19941314/a9900c87-b9df-42c1-bf6f-dae9ac1986dd)

**Comment by notestsoft** [comment]
Checking the provided screenshot it seams that the runtime data you are using is invalid. The file which couldn't be loaded is mobserver.dat from your runtime data path.

I will add a proper logging for the file handling so the error message won't be missleading in the future.
